### ISSUE TITLE
[BUG] maxplayers is getting overwritten?

### ISSUE THREAD

**Issue by keybangz** [zimsneexh/Synergy-HL2-docker#1]
Fantastic script!, I've planned to use this to play through HL2 co-op with my mates, however the maxplayer count is stuck at 2, even if I change the maxplayers count server variable inside start.sh, any ideas?

Thank you.

**Comment by zimsneexh** [comment]
You probably didn't rebuild the container image when you changed the maxplayer count in start.sh. The start.sh file is copied on buildtime.

I added a SERVER_SLOTS environment variable which should work for you.
Run: 
`docker-compose down` and pull the changes from git.
`docker-compose build`
and rerun the updated up command

**Comment by keybangz** [comment]
Alright, I'll give it ago, I definitely did rebuild the container image though.

Will report back sometime today, thank you!

**Comment by keybangz** [comment]
I have pulled the most recent version of this project, and filled out the SERVER_SLOTS variable, setting it to 6.

Ensuring to run `docker-compose down` when I close the container, running it twice whilst setting SERVER_SLOTS=6, the maxplayers is still 2.

**Comment by keybangz** [comment]
I have just realised my mistake, I am so silly, closing this issue, thank you for incorporating the SERVER_SLOTS variable, looks like I overlooked it almost twice now.

I have rebuilt the container and it is working mint.
